name: "list-objects"
replicaCount: 3
namespace: default

region: "eu-west-1"

image:
  repository: "infiejos/tier-blobility-microservice"
  pullPolicy: IfNotPresent
  # DO NOT REMOVE THIS LINE: IT IS HERE FOR AUTOMATION PURPOSES
  tag: "0.0.3"

secret:
  aws_access_key_id: ""
  aws_secret_access_key: ""
  dockerUsername: ""
  dockerPassword: ""
  dockerRegistry: "https://index.docker.io/v1/"

deployment:
  deploy: "false"
