name: "list-objects"
replicaCount: 1
namespace: default

region: "eu-west-1"

image:
  repository: "infiejos/tier-blobility-registry"
  pullPolicy: IfNotPresent
  # DO NOT REMOVE THIS LINE: IT IS HERE FOR AUTOMATION PURPOSES
  tag: "latest"

secret:
  aws_access_key_id: ""
  aws_secret_access_key: ""
  dockerUsername: ""
  dockerPassword: ""

deployment:
  deploy: "false"