apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}-deployment"
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.name }}-microservice"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}-microservice"
    spec:
      containers:
      - name: "{{ .Values.name }}-microservice"
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        env:
          - name: AWS_DEFAULT_REGION
            value: "{{ .Values.region }}"
          - name: AWS_ACCESS_KEY_ID 
            valueFrom: 
              secretKeyRef: 
                name: "{{ .Values.name }}-secret" 
                key: aws_access_key_id 
          - name: AWS_SECRET_ACCESS_KEY 
            valueFrom: 
              secretKeyRef: 
                name: "{{ .Values.name }}-secret" 
                key: aws_secret_access_key
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: "{{ .Values.name }}-regcred"