apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Values.name }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Values.name }}"
spec:
  restartPolicy: Never
  containers:
  - name: "{{ .Values.name }}"
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    env: 
      - name: AWS_ACCESS_KEY_ID 
        valueFrom: 
          secretKeyRef: 
            name: "{{ .Values.name }}-secret" 
            key: aws_access_key_id 
      - name: AWS_SECRET_ACCESS_KEY 
        valueFrom: 
          secretKeyRef: 
            name: "{{ .Values.name }}-secret" 
            key: aws_secret_access_key
    imagePullPolicy: IfNotPresent