apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-service"
spec:
  ports:
  - name: "{{ .Values.name }}-spring"
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30007
  selector:
    app: app: "{{ .Values.name }}-microservice"
  type: NodePort